### ISSUE TITLE
Printing laravel-share::laravel-share.facebook

### ISSUE THREAD

**Issue by d-arken** [jorenvh/laravel-share#11]
Hi, i did the install with the guide. 
But my outputs come
`<div id="social-links"><ul>laravel-share::laravel-share.facebook</ul></div>`
Yes, i know i have to use {!! !!} The thing is that laravel-share::laravel-share.facebook output.
in the blade file 
`          {!! Share::currentPage()->facebook() !!}`
I did something wrong?
Regards =)

**Comment by jorenvh** [comment]
What is the locale of your application?

Seems to me that their are 2 possibilities:
- The language file of the package isn't published
- The locale of your application is not "en" and you didn't create the language file in the application language

Can you check the above and get back to me?

**Comment by d-arken** [comment]
Hi Joren,
Thanks for your time,
Yes, my app language is set to pt-br, and i moved the files.
But checking now, i did a mistake with folders.
Now its working.
Thanks again, and congratz for the job =)
Regards.
