### ISSUE TITLE
Share Title is not currect

### ISSUE THREAD

**Issue by saifuldhaka** [jorenvh/laravel-share#12]
When share any product page, the share title is not same as page title. It pick the home page title.

**Comment by jorenvh** [comment]
Can you please provide more info, with the current info I'm not able to help you.

**Comment by saifuldhaka** [comment]
i want to mean page title and share page title. og_title, og_image etc.

Some how i solved it. 
@section('facebook_meta')
    <meta property="og:title" content="">
		<meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
@endsection
