### ISSUE TITLE
can i used this for other social networks sharing

### ISSUE THREAD

**Issue by yatin13490** [jorenvh/laravel-share#21]
Hi,

my requirement is I need to share with the service you provided but also need to share with Pinterest 

Can I use this package for this?

**Comment by jorenvh** [comment]
Hi

Currently we don't support Pintrest, but I'm open for a good PR to add this feature.

**Comment by icuMedia** [comment]
+1 Instagram

**Comment by kadnan** [comment]
is it done?

**Comment by Askancy** [comment]
And for Telegram?

**Comment by jorenvh** [comment]
I'd accept a PR for the suggested providers. Closing this ticket though.
