### ISSUE TITLE
For facebook sharing

### ISSUE THREAD

**Issue by vivek9716** [jorenvh/laravel-share#22]
Should we need to add og tags on my page for facebook sharing.

**Comment by jorenvh** [comment]
Hi @vivek9716 

Adding og tags is recommended but not required.

Joren

**Comment by vivek9716** [comment]
Ok thanks for quick reply 👍

**Comment by htetoozin** [comment]
@jorenvh How to change custom image share on facebook?

**Comment by jorenvh** [comment]
@htetoozin through the og tags in your html, this is not in the scope of this package. 

Closing this as the original question is answerd
