### ISSUE TITLE
Suggested CSS

### ISSUE THREAD

**Issue by syahnur197** [jorenvh/laravel-share#25]
ul { 
      overflow: auto; 
    } 
    ul li { 
      list-style-type: none; float: left; 
    } 
    ul li a span { 
      background: #205D7A; 
      color: #fff; 
      width: 40px; 
      height: 40px; 
      border-radius: 20px; 
      font-size: 25px; 
      text-align: center; 
      margin-right: 10px; 
      padding-top: 15%; 
    }

    .fa-facebook-square { 
      background:#3b5998 
    } 
    .fa-google-plus-g { 
      background:#dd4b39 
    }
    .fa-twitter { 
      background:#00aced 
    }

maybe someone can give a better design than this :)

**Comment by jorenvh** [comment]
Thank you for your contribution and sorry for the delay in my response. 
However I'm not going to add any css to the package as I want users to be free to do whatever they want with it in their application, without any default styling.
