### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by apokryfos** [jorenvh/laravel-share#29]
Full disclaimer, I have not used this library at all but it looks great so I need some more information.

I've read through the README but have not found any information about browser support. I did notice that this requires jQuery 3 so that implies IE 9+ and latest(ish) versions of other browsers.

Is jQuery 3 a strict requirement e.g. can we switch to jq 1.X (because I'm already using that version so I don't want to do noConflict unless I really have to). 

Does this library itself have any browser requirements other than what jquery (and possibly fontawesone) impose?

**Comment by jorenvh** [comment]
Jquery 3 was the latest version at the time that I published this package. No heavy JS is used so you should be good with jq 1.X.

All JS that is used by this package can be found here: https://github.com/jorenvh/laravel-share/blob/master/public/js/share.js

There are no further requirements for this package. You are always free to overwrite the JS file in your public directory with whatever you want.

I hope this helps you and sorry for the delay in my response.
