### ISSUE TITLE
Remove Google Plus Sharable Link

### ISSUE THREAD

**Issue by senbai** [jorenvh/laravel-share#36]
Hey 'laravel-share' Developers.
i just want to mention when I'm using The Package i notice  The Google Plus Link is no longer Available Anymore. 

For More Details Please See:
https://support.google.com/plus/answer/9217723?hl=en&authuser=0

![googleplus](https://user-images.githubusercontent.com/21012933/58995268-6a2e6300-87eb-11e9-96f5-abe5e56cbdc1.png)

**Comment by jorenvh** [comment]
Good suggestion, I will allocate some time in one of the coming weeks to remove Google+ support and tag a new major release of the package.
