### ISSUE TITLE
Non-static method Jorenvh\Share\Share::currentPage() should not be called statically

### ISSUE THREAD

**Issue by MajidAlaeinia** [jorenvh/laravel-share#37]
According to the [README.md](https://github.com/jorenvh/laravel-share#usage), we have to use it like that, but it leads to this error: `Non-static method Jorenvh\Share\Share::currentPage() should not be called statically`. As it says, it is caused by using `page` or `currentPage` method statically on [`Share`](https://github.com/jorenvh/laravel-share/blob/master/src/Share.php) class, but the `page` method is not defined statically.
I think this can be resolved by changing [those methods](https://github.com/jorenvh/laravel-share/blob/master/src/Share.php#L72) **statically**. Like this:
```php
public static function page(...)
{
...
}
```
Or alternatively, using the [`ShareFacade`](https://github.com/jorenvh/laravel-share/blob/master/src/ShareFacade.php) instead.

**P.S:** I have followed the [installation](https://github.com/jorenvh/laravel-share#installation) and the alias is defined.

**Comment by jorenvh** [comment]
You are using the class instead of the facade. Try using https://github.com/jorenvh/laravel-share/blob/master/src/ShareFacade.php

**Comment by MajidAlaeinia** [comment]
Right, that's what I wrote on my issue. The problem is you are giving wrong information in your (README.md)[https://github.com/jorenvh/laravel-share#usage] on how to use it.

**Comment by jorenvh** [comment]
@MajidAlaeinia I will see if I can improve the documentation, I assumed the Facade was already registered as an Alias.

**Comment by NavidAnjum** [comment]
We can always call it non-statically

return $shareComponent = (new \Jorenvh\Share\Share)->page(
			'https://www.test.com',
			'Your share text comes here'
        )
			->facebook()
			->twitter()
			->linkedin()
			->telegram()
			->whatsapp()
			->reddit();
