### ISSUE TITLE
Showing logo instead of post image

### ISSUE THREAD

**Issue by neerajprashar** [jorenvh/laravel-share#38]
When I shared post on facebook, it is showing website's logo instead of actual post image. How can we change this behaviour?

**Comment by jorenvh** [comment]
This is not something that is in the scope of this package. The package only provides the share links for the social networks of your choice. Which image that is being shown depends on the meta tags that you set for your page.

**Comment by vipertecpro** [comment]
You can make your header dynamic to do that example : if i open/view single post details so automatically my post image will be set in meta tag and then when you share it will show your post image.
