### ISSUE TITLE
Whatsapp URL Should be URLEncoded

### ISSUE THREAD

**Issue by victoryoalli** [jorenvh/laravel-share#39]
Now whatsapp It's giving an error "This link couldn´t be opened. Check the link and try again."
This is because the url now needs to be URLEncoded .

**Comment by vipertecpro** [comment]
@victoryoalli  What have you tried so far ? maybe the message body might have some special characters which is why is not creating link maybe that's the issue ?

**Comment by victoryoalli** [comment]
It happens when you use it from and iPhone, I haven't tried it using and Android device.

https://wa.me/?text=https://xochibotanicals.com/producto/crema-hidratante-para-manos-cacao/xochi

Check it out:

https://xochibotanicals.com/producto/crema-hidratante-para-manos-cacao

I modified the code and it works.
I will fork it and make a pull request if you want.

**Comment by vipertecpro** [comment]
I checked that link and its working, Good Job.

**Comment by jorenvh** [comment]
@victoryoalli do you mind sharing what went wrong and how you fixed it?

@vipertecpro thanks for helping out on the issue!
