### ISSUE TITLE
Is this production ready for laravel6 ?

### ISSUE THREAD

**Issue by vipertecpro** [jorenvh/laravel-share#45]
I was wondering when can we expect to use this in laravel6?

**Comment by sandervankasteel** [comment]
I haven't tried it yet. But I am planning to try it in the next few days. (I'm gonna update one of my projects to Laravel 6, which incidentally also uses this library).

So I will let you know how it goes :)

**Comment by jorenvh** [comment]
Haven't tried it either, but there aren't any hard dependencies so it should be working. I'm currently working on a Laravel 6 project, I will import the package later today and provide you with an update.

**Comment by vipertecpro** [comment]
Great thx a alot, and i'm WATCHING always :p.

**Comment by jorenvh** [comment]
Lost track of this issue, but the package works perfectly with Laravel 6.
