### ISSUE TITLE
sharing with multiple account automatically ?  

### ISSUE THREAD

**Issue by zheeek** [jorenvh/laravel-share#5]
Excuse me  is it possible to share links in multiple account automatically in Facebook or others  . for example share link after posted automatically in 5 account ?

**Comment by jorenvh** [comment]
Hi @zheeek 

This package is not build to actually share content. Laravel share provides a fluent way to generate social share buttons.

If you want to automatically share links I suggest you take a look at the api of the service you want to publish to.
