### ISSUE TITLE
Laravle-share using

### ISSUE THREAD

**Issue by dannylank** [jorenvh/laravel-share#51]
Hello, 
I have some troubles implementing laravel-share. I try using this code:
`Share::currentPage()->facebook();`

but I'm not sure how and where use it, if I using in controller just pass a var? or I need to use directly in view? when I use like:
 
`  <span class="post_share">{{ Share::currentPage()->facebook() }}</span>`
but show this:
 
`<div id="social-links"><ul>laravel-share::laravel-share-fa4.facebook</ul></div>`
thankyou for your help

**Comment by whoisthisstud** [comment]
> ` <span class="post_share">{{ Share::currentPage()->facebook() }}</span>`
> but show this:

@dannylank, try displaying the data unescaped... 
`<span class="post_share">{!! Share::currentPage()->facebook() !!}</span>`

**Comment by jorenvh** [comment]
Wha @whoisthisstud is saying should work.

**Comment by afrasiyabhaider** [comment]
It doesn't display anything @whoisthisstud @jorenvh

**Comment by whoisthisstud** [comment]
This is what I have and what is working for me - "jorenvanhocht/laravel-share": "^3.2",

{!! Share::page( route('your_route_name'), 'Message Content')->twitter()->facebook()->pinterest() !!}

**Comment by afrasiyabhaider** [comment]
When I dd() this code the above code is also perfectly displaying result but when I add this code into blade file to render it on page It displays blank (no result)
