### ISSUE TITLE
Error in getting share link

### ISSUE THREAD

**Issue by jaygagnani** [jorenvh/laravel-share#6]
These html tags are included in the method response i get from Share::currentPage()->facebook();
`<div id="social-links"><ul><li><a href="https://www.facebook.com/sharer/sharer.php?u=http://localhost:8000/blog/Blog-1-1497827557" class="social-button " id=""><span class="fa fa-facebook-official"></span></a></li></ul></div>`

Same is happening for all providers. These tags get added within href attribute instead of just the share url.
Solution Please!

**Comment by jorenvh** [comment]
The goal of this package is to generate those links with the icons and stuff like that. Not for generating a url. Feel free to create a PR that makes this possible.
