### ISSUE TITLE
LinkedIn share link not working

### ISSUE THREAD

**Issue by kiranajudiya** [jorenvh/laravel-share#61]
hello @jorenvh  LinkedIn update there share link so can you update that??

currently getting this error
![image](https://user-images.githubusercontent.com/17902344/97149738-2bf46380-1793-11eb-936f-087b8d540d5a.png)

2010:
`https://www.linkedin.com/cws/share?url={url}`

2015:
`https://www.linkedin.com/shareArticle?url={url}&title={title}&summary={text}&source={provider}`

2020:
`https://www.linkedin.com/sharing/share-offsite/?url={url}`

here is document link [https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/share-plugin](url)

**Comment by jorenvh** [comment]
Thank you for pointing this out. I'm currently a bit short in time would you mind creating a PR that fixes the issue?

**Comment by jorenvh** [comment]
@kiranajudiya thanks for pointing this out. I just released v4 of the package with an updated base url for Linkedin. 

Thank you for your patience!
