### ISSUE TITLE
buttons isnt' works

### ISSUE THREAD

**Issue by Heqma** [jorenvh/laravel-share#62]
Hi, i was do all steps. 
`{{!! Share::page('http://jorenvanhocht.be')->facebook(); !!}} `

return: 

`<div id="social-links"><ul>laravel-share::laravel-share-fa4.facebook</ul></div>`

**Comment by jorenvh** [comment]
Have you followed all installation instructions as mentioned in the readme?

`php artisan vendor:publish --provider="Jorenvh\Share\Providers\ShareServiceProvider"`

**Comment by Heqma** [comment]
yes, i even change version of fontawesome to 5 in laravel share inside config

**Comment by jorenvh** [comment]
Can you confirm that the language file is available in `resources/lang/vendor/en/`. Please note that that if you use another language as en that you might need to create extra files for these languages.

**Comment by Heqma** [comment]
Ok, it looks like to working except linkedin

**Comment by jorenvh** [comment]
Related to #61

**Comment by jorenvh** [comment]
Fixed in v4 of the package that has just been released
