### ISSUE TITLE
Wrong examples in calling the methods

### ISSUE THREAD

**Issue by jadayash** [jorenvh/laravel-share#64]
Hello
Thanks for this nice package.
According to the examples posted, the calling of the method is static (Share::page...)

In fact these methods aren't static so they should be called

$share = new Share();
$share->page(request()->url())->facebook()
$share->currentPage()->onlyLinks()

**Comment by jorenvh** [comment]
The example assumes that you are using the Laravel Facade. 

```
// config/app.php
'aliases' => [
    'Share' => Jorenvh\Share\ShareFacade::class,
];
```
