### ISSUE TITLE
how can i customize facebook icon.

### ISSUE THREAD

**Issue by sohil123123** [jorenvh/laravel-share#65]
Description : I am trying to add below code in my laravel app

		{!! Share::currentPage('')
->facebook()
->twitter()
->linkedin('Football4Football')
->whatsapp() !!}

its showing all social media default icon. i want to put my custom created icon image
can you gude me way how to do it ?

**Comment by jorenvh** [comment]
This package currently has no support for custom icons. Font Awesome 5, which this package supports, does have an option to add custom icons.
