### ISSUE TITLE
No method inside the Share.php is static method + Add view count of share?

### ISSUE THREAD

**Issue by believemaster** [jorenvh/laravel-share#66]
There is a problem accessing the methods statically but as soon as I checked Share.php methods are not static, 
```
$share = new Share; 

$share->currentPage()->facebook();
```
Object is to be created to use the methods. Otherwise it will show the error the no static method. 
I guess docs should be updated the package with static function.

Also my recommendation to add share viewcount for counting number of shares. Is there any possible way to do that?

**Comment by jorenvh** [comment]
The package leverages Laravel Facades. For more information: 

- https://github.com/jorenvh/laravel-share/blob/master/src/ShareFacade.php
- https://laravel.com/docs/8.x/facades
