### ISSUE TITLE
image not showing

### ISSUE THREAD

**Issue by myorcloud** [jorenvh/laravel-share#68]
Hello , 
i have an ecommerce  website and i'm trying to share my products in facebook using your
package however when i do share a product the thumbnail  doesn't appear on facebook 
it juste appears like this on facebook 

<img width="383" alt="Capture" src="https://user-images.githubusercontent.com/42510618/123812463-04d6ce80-d8ec-11eb-9568-72554c7d25c8.PNG">

**Comment by nisarr** [comment]
You need to set `og:image` meta tag.

<meta property="og:image" content="URL_OF_THUMBNAIL" />

https://developers.facebook.com/docs/sharing/webmasters/images.

**Comment by jorenvh** [comment]
@nisarr thanks for answering this question.
