### ISSUE TITLE
Share on linked in doesn't work 

### ISSUE THREAD

**Issue by TasneemWahdan** [jorenvh/laravel-share#86]
Thanks for this package,
It's working properly except for the LinkedIn. When I click on LinkedIn share button The URL generated is  something like this:
https://www.linkedin.com/sharing/share-offsite/?mini=true&url=https://staging.medeventus.com/events/66/Medeventus%20First%20Event

and LinkedIn page says: Something went wrong
Would  you please help me to solve this issue?

**Comment by 3gHub** [comment]
I have got the same issue. Kindly fix it.  @jorenvh @pqrs @sandervankasteel @freekmurze  
Kindly fix this issue.
Also Facebook, Twitter and LinkedIn share is not opening on new tab like whatsapp and telegram

**Comment by jorenvh** [comment]
I don't have the time for it, but feel free to open a PR to fix this problem and a working test suite

**Comment by Hashir12** [comment]
@TasneemWahdan i am also facing same issue, have you fixed it ??

**Comment by TasneemWahdan** [comment]
@Hashir12 I used [addThis](https://www.addthis.com/) for sharing

**Comment by Bolibick** [comment]
The same problem... Linkedin not working

**Comment by TasneemWahdan** [comment]
I am using the package and LinkedIn share is working now!
make sure to include these into website's head section:

        <meta property='og:title' content='Title of the article'/>
        <meta property='og:image' content='//media.example.com/ 1234567.jpg'/>
        <meta property='og:description' content='Description that will show in the preview'/>
        <meta property='og:url' content='//www.example.com/URL of the article'/> 

and clear the browser's cache  since  the error may appear there, or use another device to check
