### ISSUE TITLE
I got error    Jorenvh\Share\ShareServiceProvider' not found

### ISSUE THREAD

**Issue by amitnarmadatech** [jorenvh/laravel-share#9]
i got error Class 'Jorenvh\Share\ShareServiceProvider' not found
install fresh  new version laravel  5.1  and follow all instruction  properly

**Comment by tatarysh** [comment]
I have the same problem.

Laravel 5.5.

**Comment by jorenvh** [comment]
Sorry for the delay, it was a very busy month at the office. This is fixed in version 1.0.4. Thank you for your patience!
