### ISSUE TITLE
icons share cant show

### ISSUE THREAD

**Issue by gusvinandaellya** [jorenvh/laravel-share#98]
help, i've followed the instructions, but the icon wont appear.. 

**BLADE**
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />`
`<div class="social-btn-sp">
            {!! $shareButtons !!}
          </div>`

**CONTROLLER**
`$shareButtons = \Share::page(
			'https://keerom-bapelitbangda.com/'
		)
		->facebook()
		->twitter()
		->linkedin()
		->telegram()
		->whatsapp()
		->reddit();`
return

> laravel-share::laravel-share-fa5.facebooklaravel-share::laravel-share-fa5.twitterlaravel-share::laravel-share-fa5.linkedinlaravel-share::laravel-share-fa5.telegramlaravel-share::laravel-share-fa5.whatsapplaravel-share::laravel-share-fa5.reddit

Pls Help me..

**Comment by devkyo** [comment]
Hello, if your app is configured in a language other than 'en' it does not appear, you have to make a copy of the 'en' directory to the language of your choice in resource/lang , it is the same as the lang of the languages, copy and edit it to your preferred language that is your config/app.php

**Comment by goodmuyis** [comment]
Can you check if add blocker is not blocking the rendered HTML?
Try to open your page on incognito as well. I struggle with this for over 2 hours before I figure out that add blocker is hiding the share button
